// Code generated by god. DO NOT EDIT.
package handler

import (
	"net/http"

	open "github.com/gotid/wechat/api/internal/handler/open"
	"github.com/gotid/wechat/api/internal/svc"

	"github.com/gotid/god/api"
)

func RegisterHandlers(engine *api.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]api.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/wechat/open/:platformID/notify",
				Handler: open.NotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/wechat/open/:platformID/auth",
				Handler: open.AuthHandler(serverCtx),
			},
		},
	)
}
